import type { Metadata } from "next";
import { Geist, Geist_Mono, Exo_2, Manrope} from "next/font/google";
import "./globals.css";
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const exo2 = Exo_2({
  subsets: ['latin'],
  variable: '--font-exo-2',
  display: 'swap',
});


const manrope = Manrope({
  variable: "--font-manrope-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sua Casa Conectada",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${manrope.variable} ${exo2.variable} antialiased  bg-white overflow-x-hidden`}
      >
        {children}
      </body>
    </html>
  );
}
